version: '3.4'

services:
  granulersampleclusternode:
    image: ${DOCKER_REGISTRY-}granulersampleclusternode
    networks:
      my_network:
        ipv4_address:  192.168.3.10
    depends_on:
      - redis
    ports:
      - "11111:11111" 
      - "30000:30000"
    build:
      context: .
      dockerfile: GranulerSampleClusterNode/Dockerfile

  granulersampleclient:
    image: ${DOCKER_REGISTRY-}granulersampleclient
    networks:
      my_network:
        ipv4_address:  192.168.3.12
    depends_on:
      - granulersampleclusternode
    build:
      context: .
      dockerfile: GranulerSampleClient/Dockerfile


  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - db-data:/data/redis
    ports:
      - "6379:6379" 
    networks:
      my_network:
        ipv4_address:  192.168.3.13
volumes:
  db-data:
networks:
  my_network:
   ipam:     
      driver: default
      config:
        - subnet: 192.168.3.0/24